---
title: "Comités"
---

<br/>

## Comité organizador
- [Olga Cecilia Usuga Manco](https://www.meetup.com/es/rladies-medellin/), Universidad de Antioquia.
- [Carmen Elena Patiño Rodríguez](https://www.meetup.com/es/rladies-medellin/), Universidad de Antioquia.
- [Martha Catalina Ospina Hernández](https://www.unad.edu.co/), Universidad Nacional Abierta y a Distancia.
- [Romario Ademir Conto López](https://www.itm.edu.co/), Institución Universitaria ITM.
- [Freddy Hernández Barajas](https://fhernanb.github.io/), Universidad Nacional de Colombia, sede Medellín.
- [Jorge I. Vélez](https://jorgeivanvelez.netlify.app/), Universidad del Norte.

<br/>

## Comité científico
- [David Rodríguez Guevara](https://www.itm.edu.co/), Institución Universitaria ITM.
- [Jonathan Cano Bedoya](https://www.itm.edu.co/), Institución Universitaria ITM.
- [Diana Marcela Pérez Valencia](https://www.ehu.eus/es/home), Universidad del País Vasco.
- [Jessica María Rojas Mora](https://www.itm.edu.co/), Institución Universitaria ITM.
- [Sara Garces Cespedes](https://www.meetup.com/es/rladies-medellin/).
- [Maria Valentina Clavijo Mesa](https://www.meetup.com/es/rladies-medellin/).
- [Luz Marcela Restrepo Tamayo](https://udemedellin.edu.co/), Universidad de Medellín.
- [Eddy Herrera Daza](https://www.javeriana.edu.co/inicio), Pontificia Universidad Javeriana.

<br/>

## Contacto
Para comunicarse con la organización del evento puede escribir al correo: rdaycolombia@gmail.com
