---
title: "Concurso"
---

# __Concurso de diseño del Logotipo Rday Medellín 2019__

El Comité Organizador del Rday Medellín 2019 organiza y desarrolla el concurso de Diseño __Logotipo Rday Medellín 2019__.

## 1. Objetivo
El concurso tiene la finalidad de escoger la mejor propuesta para el evento. El logotipo deberá facilitar su identificación en el ámbito de eventos en R, diferenciarlo de eventos similares y convertirse en su imagen representativa para esta primera versión. 

## 2. Participantes
Podrán participar gratuitamente todas las personas interesadas en el evento que se acojan a las siguientes bases.

## 3. Generalidades
Los trabajos deberán ser originales e inéditos, siendo el autor responsable de las acciones que se pudieran derivar del incumplimiento de alguna de estas normas. Cada participante puede presentar máximo una (1) propuesta.

El contenido del diseño deberá hacer referencia al espíritu de eventos académicos de R, teniendo en cuenta que el logotipo será reproducido en documentos escritos, páginas web, redes sociales, etc.; además el logotipo deberá ser: 

- Legible hasta el tamaño más pequeño.  
- Escalable a cualquier tamaño requerido.  
- Reproducible sin restricciones materiales.
- Memorable: que impacte y no se olvide.

## 4. Fechas
Apertura del concurso: 4 de febrero de 2019. 

Recibo de Propuestas: Hasta las 4:00 p.m. del 13 de febrero de 2019, en el correo electrónico rdaymedellin@gmail.com.

## 5. Presentación de las propuestas
Cada diseño deberá presentarse en formato electrónico (vía e-mail). El diseño deberá entregarse en formato vectorial (por ejemplo SVG) y ser escalable. Se entregará el logotipo aislado versión color y logotipo aislado versión escala de grises (o blanco y negro).

## 6. Jurados
El jurado estará conformado por el Grupo organizador del evento. 

## 7. Premio
Se otorgará como premio la inscripción al evento y un reconocimiento público el día de la inauguración del evento. 

## 8. Propiedad intelectual y derechos de reproducción
La propiedad del logotipo premiado se cederá al evento Rday Medellín 2019, el cual se reserva todos los derechos de propiedad y uso.
El evento Rday Medellín 2019 se reserva el derecho de reproducción mediante los formatos y a través de los medios que considere oportunos, el derecho de modificar el logotipo a fin de optimizarlo para su posterior impresión, el de adaptar el logotipo cuando las características del material o el objeto sobre el que se va a reproducir no permitan hacerlo de manera completa, o también el de hacer uso por separado de los elementos del logotipo.

## 9. Aceptación de las Bases
La participación en esta convocatoria supone el conocimiento y la total aceptación de las presentes bases por parte de los autores.

