---
title: "Código de conducta"
---
<P ALIGN="justify">
Todos en nuestro evento deben estar de acuerdo con el siguiente código de conducta. Los organizadores haremos cumplir este código durante todo el evento. Esperamos la cooperación de todos los participantes para ayudar a garantizar un entorno seguro para todos.
<P>

# ¿Necesita ayuda?
Si tiene alguna duda sobre el evento puede escribir a los correos electrónicos rdaycolombia@gmail.com

# Versión corta
<P ALIGN="justify">
Esperamos que Rday sea un evento libre de acoso para todos, independientemente del sexo, identidad, género, edad, orientación sexual, discapacidad, apariencia física, tamaño corporal, raza, etnia, religión (o la falta de ella), ideología u opciones tecnológicas. No toleramos el acoso de los participantes del evento de ninguna forma. El lenguaje sexual y las imágenes no son apropiados para ningún lugar del evento, incluídas charlas, talleres, fiestas, redes sociales y otros medios en línea. Los participantes del evento que violen estas reglas pueden ser sancionados o expulsados del evento sin un reembolso a discreción de los organizadores del evento.
<P>

# Versión menos corta
<P ALIGN="justify">
El acoso incluye comentarios verbales ofensivos relacionados con el género, identidad y expresión de género, edad, orientación sexual, discapacidad, apariencia física, tamaño corporal, raza, origen étnico, religión, ideología, elección de tecnología, imágenes sexuales en espacios públicos, intimidación deliberada, acoso, seguimiento, acoso fotográfico o grabación, interrupción sostenida de las conversaciones u eventos, contacto físico inapropiado y atención sexual no deseada.
<P>

<P ALIGN="justify">
Esperamos que aquellos participantes a quienes se les solicite detener cualquier comportamiento de acoso cumplan inmediatamente. Si un participante se involucra en un comportamiento de acoso, los organizadores del evento pueden tomar las medidas que consideren apropiadas, tales como una advertencia o la expulsión del evento sin reembolso.
<P>

<P ALIGN="justify">
Si lo hostigan, observa que alguien más está siendo hostigado o tiene comentarios al respecto, comuníquese de inmediato con personal del evento. El personal del evento puede ser identificado a través de su credencial.
<P>

<P ALIGN="justify">
El personal del evento ayudará a los participantes a ponerse en contacto con la seguridad del lugar, proporcionar escoltas o ayudar a quienes sufren acoso a sentirse seguros durante la conferencia. Valoramos su asistencia al Rday.
<P>

<P ALIGN="justify">
Esperamos que los participantes sigan estas reglas tanto durante el evento como en eventos sociales relacionados con las mismas.
<P>

Adaptado de http://confcodeofconduct.com.
